# === DCAT Catalog ===
# Based on https://github.com/gdcc/exporter-dcat3/blob/c012a82e36c3de35f2bded2fbf1735a049214f8c/application_profiles/lightweight/mapping/dcat-catalog.properties
subject.iri.const = https://health-study-hub.de

props.title_en.predicate = dct:title
props.title_en.as        = literal
props.title_en.lang      = en
props.title_en.const     = NFDI4Health Health Study Hub

props.description_en.predicate = dct:description
props.description_en.as        = literal
props.description_en.lang      = en
props.description_en.const     = The Health Study Hub is the central platform for clinical, public health and epidemiological studies in Germany - with questionnaires, datasets, registries and more, openly documented for the research community.

nodes.publisher.kind = bnode
nodes.publisher.type = foaf:Agent
nodes.publisher.props.name_en.predicate = foaf:name
nodes.publisher.props.name_en.as        = literal
nodes.publisher.props.name_en.lang      = en
nodes.publisher.props.name_en.const     = ZB MED - Information Centre for Life Sciences

props.publisher.predicate = dct:publisher
props.publisher.as        = node-ref
props.publisher.node      = publisher

nodes.contact.kind = bnode
nodes.contact.type = vcard:Kind
nodes.contact.props.fn_en.predicate = vcard:fn
nodes.contact.props.fn_en.as        = literal
nodes.contact.props.fn_en.lang      = en
nodes.contact.props.fn_en.const     = NFDI4Health Helpdesk

nodes.contact.props.email.predicate = vcard:hasEmail
nodes.contact.props.email.as        = iri
nodes.contact.props.email.const     = mailto:helpdesk@nfdi4health.de

props.contactPoint.predicate = dcat:contactPoint
props.contactPoint.as        = node-ref
props.contactPoint.node      = contact
