# === DCAT Distribution ===
# Based on https://github.com/gdcc/exporter-dcat3/blob/c012a82e36c3de35f2bded2fbf1735a049214f8c/application_profiles/lightweight/mapping/dcat-distribution.properties
scope.json = $.datasetFileDetails[*]

# Subject IRI (choose your canonical scheme)
subject.iri.json.1 = $$.env.apiBaseUrl
subject.iri.json.2 = $.id
subject.iri.format = ${1}/access/datafile/${2}

# Access URL (IRI) from dataset persistent URL (root)
props.accessURL.predicate = dcat:accessURL
props.accessURL.as        = iri
props.accessURL.json      = $$.datasetJson.persistentUrl

# License from datasetVersion (if available)
props.license.predicate = dcterms:license
props.license.as        = node-ref
props.license.node      = license

nodes.license.kind = bnode
nodes.license.type = dcterms:LicenseDocument

nodes.license.props.title.predicate = dct:title
nodes.license.props.title.as        = literal
nodes.license.props.title.lang      = en
nodes.license.props.title.json      = $$.datasetJson.datasetVersion.license.name

# Title
props.title.predicate = dct:title
props.title.as        = literal
props.title.json      = $.filename

# Description
props.description.predicate = dct:description
props.description.as        = literal
props.description.lang      = en
props.description.json      = $.description

# Byte size ? xsd:integer (datatype IRI must be expanded by mapper)
props.byteSize.predicate = dcat:byteSize
props.byteSize.as        = literal
props.byteSize.datatype  = xsd:integer
props.byteSize.json      = $.filesize

# Media type (IRI to IANA)
props.mediaType.predicate = dcat:mediaType
props.mediaType.as        = iri
props.mediaType.format    = http://www.iana.org/assignments/media-types/${value}
props.mediaType.json      = $.contentType

# SPDX checksum node with algorithm mapped from $.checksum.type
props.checksum.predicate = spdx:checksum
props.checksum.as        = node-ref
props.checksum.node      = checksum

nodes.checksum.kind = bnode
nodes.checksum.type = spdx:Checksum

nodes.checksum.props.algorithm.predicate = spdx:algorithm
nodes.checksum.props.algorithm.as        = iri
nodes.checksum.props.algorithm.json      = $.checksum.type
nodes.checksum.props.algorithm.map.MD5    = spdx:checksumAlgorithm_md5
nodes.checksum.props.algorithm.map.SHA1   = spdx:checksumAlgorithm_sha1
nodes.checksum.props.algorithm.map.SHA-1  = spdx:checksumAlgorithm_sha1
nodes.checksum.props.algorithm.map.SHA224 = spdx:checksumAlgorithm_sha224
nodes.checksum.props.algorithm.map.SHA-224= spdx:checksumAlgorithm_sha224
nodes.checksum.props.algorithm.map.SHA256 = spdx:checksumAlgorithm_sha256
nodes.checksum.props.algorithm.map.SHA-256= spdx:checksumAlgorithm_sha256
nodes.checksum.props.algorithm.map.SHA512 = spdx:checksumAlgorithm_sha512
nodes.checksum.props.algorithm.map.SHA-512= spdx:checksumAlgorithm_sha512

nodes.checksum.props.checksumValue.predicate = spdx:checksumValue
nodes.checksum.props.checksumValue.as        = literal
nodes.checksum.props.checksumValue.json      = $.checksum.value
