apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-mongodb-backup
spec:
  schedule: "30 7 * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - image: {{ .Values.mongo.image}}
              name: db-backup
              env:
                - name: S3_KEY
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Release.Name }}-s3-backup-secret
                      key: key
                - name: S3_KEYID
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Release.Name }}-s3-backup-secret
                      key: keyid
                - name: S3_HOST
                  value: {{ .Values.backup.s3.host }}
                - name: S3_BUCKET
                  value: {{ .Values.backup.s3.bucket }}
                - name: MONGO_HOST
                  value: {{ .Release.Name }}-mongo
                - name: MONGO_PORT
                  value: "27017"
                - name: MONGO_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Release.Name }}-mongo-secret
                      key: username
                      optional: false
                - name: MONGO_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Release.Name }}-mongo-secret
                      key: password
                      optional: false
                - name: RELEASE_NAME
                  value: {{ .Release.Name }}
              command: [ "/bin/sh","-c" ]
              args: [ "apt-get update;
              apt-get install -y s3cmd;
              mongodump --host=$MONGO_HOST --username=$MONGO_USERNAME --password=$MONGO_PASSWORD --authenticationDatabase=admin --gzip --archive=${RELEASE_NAME}_$(date +%Y-%m-%d).archive.gz;
              s3cmd --host=${S3_HOST} --access_key=${S3_KEYID} --secret_key=${S3_KEY} --host-bucket=${S3_BUCKET}.${S3_HOST} put ${RELEASE_NAME}_$(date +%Y-%m-%d).archive.gz s3://${S3_BUCKET}/${RELEASE_NAME}_$(date +%Y-%m-%d).archive.gz" ]
          restartPolicy: Never
      backoffLimit: 2
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-s3-backup-secret
type: Opaque
data:
  key: {{ .Values.backup.s3.key | b64enc| quote}}
  keyid: {{ .Values.backup.s3.keyid |b64enc| quote}}

