version: '3'
services:
  db: # Database implementation, in this case MySQL
    image: mysql:5.7
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    stop_grace_period: 1m30s
    env_file:
      - db.env
    volumes:
      - seek-mysql-db:/var/lib/mysql

  seek: # The SEEK application
    image: gitlab.zbmed.de:5050/nfdi4health/registersearch/seek-nfdi4health:da90c422faf5473c2a0e00afba023d50c194cdba
    command: docker/entrypoint.sh
    restart: always
    environment:
      RAILS_ENV: production
      RAILS_RELATIVE_URL_ROOT: "/mdr"
      SOLR_PORT: 8983
      SOLR_HOST: solr
      NO_ENTRYPOINT_WORKERS: 1
    env_file:
      - db.env
    volumes:
      - seek-filestore:/seek/filestore
      - seek-cache:/seek/tmp/cache
    ports:
      - "3000:3000"
    depends_on:
      - db
      - solr
    links:
      - db
      - solr

  seek_workers: # The SEEK delayed job workers
      image: gitlab.zbmed.de:5050/nfdi4health/registersearch/seek-nfdi4health:da90c422faf5473c2a0e00afba023d50c194cdba
      command: docker/start_workers.sh
      restart: always
      environment:
        RAILS_ENV: production
        SOLR_PORT: 8983
        SOLR_HOST: solr
      env_file:
        - db.env
      volumes:
        - seek-filestore:/seek/filestore
        - seek-cache:/seek/tmp/cache
      depends_on:
        - db
        - solr
      links:
        - db
        - solr

  solr:
    image: fairdom/seek-solr:8.11
    restart: always
    environment:
      SOLR_JAVA_MEM: -Xms512m -Xmx1024m
    volumes:
      - seek-solr-data:/var/solr/
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - seek
      - /opt/solr/server/solr/configsets/seek_config      


volumes:
  seek-filestore:
#    external: true
  seek-mysql-db:
#    external: true
  seek-solr-data:
#    external: true
  seek-cache:
 #   external: true
