# configure K8s cron job managed by the operator
configLogicalBackup:
  # Install Keycloak Operator
  # image for pods of the logical backup job (example runs pg_dumpall)
  logical_backup_docker_image: "registry.opensource.zalan.do/acid/logical-backup:v1.10.0"
  # path of google cloud service account json file
  # logical_backup_google_application_credentials: ""
  # prefix for the backup job name
  logical_backup_job_prefix: "logical-backup-"
  # storage provider - either "s3" or "gcs"
  logical_backup_provider: "s3"
  # S3 endpoint url when not using AWS
  logical_backup_s3_endpoint: "https://s3.de-west-1.psmanaged.com"
  # S3 bucket to store backup results
  logical_backup_s3_bucket: "postgres-test"
  # S3 Access Key ID
  logical_backup_s3_access_key_id: ""
  # S3 Secret Access Key
  logical_backup_s3_secret_access_key: ""
  # S3 server side encryption
  logical_backup_s3_sse: "AES256"
  # S3 retention time for stored backups for example "2 week" or "7 days"
  logical_backup_s3_retention_time: "1 month"
  # backup schedule in the cron format
  logical_backup_schedule: "1 * * * *"
# Only useful for non-productive installations https://github.com/zalando/postgres-operator/blob/master/docs/administrator.md#pod-disruption-budget**********
enable_pod_disruption_budget: false