#https://github.com/zalando/postgres-operator/blob/master/docs/quickstart.md
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name:  {{ .Release.Name }}-dataverse-postgres
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/instance: postgres-{{ .Release.Name }}
    app.kubernetes.io/version: "14"
    app.kubernetes.io/component: postgres
    app.kubernetes.io/part-of: dataverse
spec:
  enableLogicalBackup: {{ .Values.postgres.logical_backup }}
  teamId:  {{ .Release.Name }}
  volume:
    size:  {{ .Values.postgres.volume_size }}
  numberOfInstances: {{ int .Values.postgres.number_instances }}
  {{ if gt (int .Values.postgres.number_instances) 1 }}
  enableConnectionPooler: true
  connectionPooler:
   mode: session
  {{ end }}
  users:
    dataverse:  # database owner
    - superuser
    - createdb
  databases:
    dataverse: dataverse  # dbname: owner
  postgresql:
    version: "14"
---
