apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: html-volume
              mountPath: /usr/share/nginx/html
      volumes:
        - name: html-volume
          configMap:
            name: {{ .Release.Name }}-html
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-html
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Under Maintenance</title>
      <style>
        @font-face {
          font-family: "Roboto";
          src: url("Roboto-Regular.ttf") format("truetype");
          font-style: normal;
        }
    
        body {
          font-family: Roboto,"Apple Color Emoji","Segoe UI Emoji","Segoe UI Symbol",sans-serif;
          background-color: rgb(229, 229, 229);
          color: #343741;
          text-align: center;
          font-size: 16px;
          font-weight: 400;
        }
      </style>
    </head>
    <body>
      <img src="NFDI4Health_Logo_cmyk_RZ.svg" alt="NFDI4Health Logo" width="500">
      <h1>This service is currently under maintenance</h1>
      <p>We are performing maintenance work to improve our service. It will be back online soon, usually within a few hours.</p>
      <p>We apologize for any inconvenience and appreciate your understanding.</p>
    </body>
    </html>
  NFDI4Health_Logo_cmyk_RZ.svg: |
    {{ .Files.Get "files/NFDI4Health_Logo_cmyk_RZ.svg" | nindent 4 | trim }}
binaryData:
  Roboto-Regular.ttf: |
    {{ .Files.Get "files/fonts/Roboto-Regular.ttf" | b64enc }}
