apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend
spec:
  selector:
    matchLabels:
      name: {{ .Release.Name }}-backend
  template:
    metadata:
      labels:
        name: {{ .Release.Name }}-backend
    spec:
      containers:
      - image: {{ .Values.images.backend }}
        name: backend
        env:
          - name: MONGO_HOST
            value: "{{ .Release.Name }}-mongo"
          - name: MONGO_PORT
            value: "27017"
          - name: MONGO_USERNAME
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-mongo-secret
                key: username
                optional: false
          - name: MONGO_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-mongo-secret
                key: password
                optional: false
          - name: API_PROJECT
            value: "{{ .Values.api.default_project }}"
          - name: API_HOST_SEEK
            value: "http://{{ .Release.Name }}-seek-backend:3000/mdr"
          - name: API_TOKEN
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-backend-secret
                key: token
          - name: ELASTIC_INDEX
            value: test
          - name: ELASTIC_URL
            value: http://{{ .Release.Name }}-elastic:9200
          - name: CLIENT_ID
            value: {{ .Values.oidc.backend.clientid }}
          - name: CLIENT_SECRET
            value: {{ .Values.oidc.backend.secret }}
          - name: INTROSPECT_URL
            value: {{ .Values.oidc.backend.introspect }}
        ports:
          - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend
spec:
  ports:
    - name: "5000"
      port: 5000
      targetPort: 5000
  selector:
    name: {{ .Release.Name }}-backend
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-backend-secret
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
data:
  token: {{ default "" .Values.api.default_token | b64enc | quote }}
