apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend
spec:
  selector:
    matchLabels:
      name: {{ .Release.Name }}-backend
  template:
    metadata:
      labels:
        name: {{ .Release.Name }}-backend
    spec:
      containers:
      - image: {{ .Values.images.backend }}
        name: backend
        env:
          - name: API_HOST
            # @TODO: Also use the secret here.
            value: mongodb://root:example@{{ .Release.Name }}-mongo:27017/resources?authSource=admin
          - name: API_PROJECT
            value: "{{ .Values.api.default_project }}"
          - name: API_TOKEN
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-backend-secret
                key: token
          - name: ELASTIC_INDEX
            value: test
          - name: ELASTIC_URL
            value: http://{{ .Release.Name }}-elastic:9200
        ports:
          - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend
spec:
  ports:
    - name: "5000"
      port: 5000
      targetPort: 5000
  selector:
    name: {{ .Release.Name }}-backend
---
{{- $secret := (lookup "v1" "Secret" .Release.Namespace "{{ .Release.Name }}-backend-secret") -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-backend-secret
type: Opaque
{{ if $secret -}}
data:
  token: {{ $secret.token }}
{{ else -}}
data:
  token: {{ default "" .Values.api.default_token | b64enc | quote }}
{{ end }}
