{{- if and .Values.frontend.seoRenderer.enabled (empty .Values.frontend.basicAuth.htpasswd) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-frontend-seo-renderer
spec:
  replicas: {{ .Values.frontend.seoRenderer.replicaCount }}
  selector:
    matchLabels:
      name: {{ .Release.Name }}-frontend-seo-renderer
  template:
    metadata:
      labels:
        name: {{ .Release.Name }}-frontend-seo-renderer
    spec:
      containers:
        - name: frontend-seo
          image: {{ .Values.images.seoRenderer }}
          ports:
            - name: http
              containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: INDEX_HTML_PATH
              value: "/app/build/index.html"
            - name: DATAVERSE_API_BASE_URL
              value: "http://{{ .Release.Name }}-backend:5000/api"
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          resources:
            {{ toYaml .Values.frontend.seoRenderer.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-frontend-seo-renderer
spec:
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  selector:
    name: {{ .Release.Name }}-frontend-seo-renderer
{{- end }}