# Get login data and user info from SEEK DB
# SELECT t.login,t.id, p.first_name, p.last_name,p.email,p.phone,p.web_page,p.orcid
# FROM seek_docker.users t JOIN people p on t.person_id = p.id
# ORDER BY login
# LIMIT 501;

### Authenticate Admin
POST https://keycloak.qa.km.k8s.zbmed.de/realms/master/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

username=admin&password={{PW}}&grant_type=password&client_id=admin-cli&client_secret={{secret}}
> {%
    client.global.set("auth_token", response.body.access_token);
%}


### Create User
POST https://keycloak.qa.km.k8s.zbmed.de/admin/realms/nfdi4health/users
Accept: application/json
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "username": "{{username}}",
  "email": "{{email}}",
  "firstName": "{{firstname}}",
  "lastName": "{{lastname}}",
  "attributes": {
        "SEEK_USER": "{{seek_user}}",
        "orcid": "{{orcid}}",
        "phone": "{{phone}}",
        "web_page": "{{webpage}}"
  },
  "enabled": true,
  "emailVerified": true,
  "requiredActions": ["UPDATE_PASSWORD"]
}


### Find User
GET https://keycloak.qa.km.k8s.zbmed.de/admin/realms/nfdi4health/users
Accept: application/json
Authorization: Bearer {{auth_token}}
Content-Type: application/json

# "id": "272cb39c-ec1b-4911-b6ec-192058375ad2",
#  "attributes": {
#      "SEEK_USER_ID": [
#        "1"
#      ]
#    },