apiVersion: batch/v1
kind: Job
metadata:
  name: dataverse-publish-job
spec:
  template:
    spec:
      containers:
        - name: dataverse-scripts
          image: ghcr.io/nfdi4health/csh-etl-pipeline:latest
          env:
            - name: DATAVERSE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: dataverse-publish-job-secret
                  key: DATAVERSE_API_KEY
          command:
            - "python"
            - "-u" # unbuffered, so logs are immediately flushed
            - "scripts/publish_all_datasets.py"
            - "-d http://$DATAVERSE_NAME-svc:8080"
            - "-k"
            - "$(DATAVERSE_API_KEY)"
            - "-t"
            - "$DATAVERSE_PUBLISH_TYPE"
            - "-c"
            - "$DATAVERSE_COLLECTIONS"
      restartPolicy: OnFailure
---
apiVersion: v1
kind: Secret
metadata:
  name: dataverse-publish-job-secret
data:
  DATAVERSE_API_KEY: $DATAVERSE_API_KEY_B64