apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-extract-job
spec:
  schedule: {{ .Values.schedule | quote }}
  timeZone: {{ .Values.timeZone | quote }}
  suspend: {{ .Values.suspend }}
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: extract
              image: {{ printf "%s:%s" .Values.image.repository .Values.image.tag }}
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              env:
                - name: AWS_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Release.Name }}-credentials
                      key: AWS_ACCESS_KEY_ID
                - name: AWS_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Release.Name }}-credentials
                      key: AWS_SECRET_ACCESS_KEY
                - name: AWS_ENDPOINT_URL
                  value: {{ .Values.s3.endpointUrl | quote }}
                - name: S3_PATH
                  value: {{ printf "%s/%s" (.Values.s3.basePath | replace "s3://" "") (lower .Values.source) | quote }}
              command:
                - /bin/sh
                - -c
              args:
                - >
                  EXTRACT_PATH=$(echo "${S3_PATH}/$(date +%Y-%m-%d).parquet");
                  if aws s3 ls s3://${EXTRACT_PATH}/_SUCCESS --endpoint-url=$AWS_ENDPOINT_URL; then
                    echo "Parquet file already exists, skipping."
                    exit 0
                  fi;
                  python3 -u etljobs/extract/extract_{{ lower .Values.source }}_data.py --temp-dir /tmp/extract --output s3://$EXTRACT_PATH
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-transform-job
spec:
  schedule: {{ .Values.schedule | quote }}
  timeZone: {{ .Values.timeZone | quote }}
  suspend: {{ .Values.suspend }}
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          initContainers:
            - name: wait-for-extract
              image: amazon/aws-cli
              env:
                - name: AWS_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Release.Name }}-credentials
                      key: AWS_ACCESS_KEY_ID
                - name: AWS_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Release.Name }}-credentials
                      key: AWS_SECRET_ACCESS_KEY
                - name: AWS_ENDPOINT_URL
                  value: {{ .Values.s3.endpointUrl | quote }}
                - name: S3_PATH
                  value: {{ printf "%s/%s" (.Values.s3.basePath | replace "s3://" "") (lower .Values.source) | quote }}
              command: ["sh", "-c"]
              args:
                - >
                  EXTRACT_PATH="${S3_PATH}/$(date +%Y-%m-%d).parquet";
                  echo "Waiting for s3://$EXTRACT_PATH...";
                  until aws s3 ls s3://$EXTRACT_PATH/_SUCCESS --endpoint-url=$AWS_ENDPOINT_URL; 
                  do sleep 10; done
          containers:
            - name: spark-submit
              image: {{ printf "%s:%s" .Values.image.repository .Values.image.tag }}
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              env:
                - name: SOURCE
                  value: {{ .Values.source | quote }}
                - name: S3_PATH
                  value: {{ printf "%s/%s" (.Values.s3.basePath | replace "s3://" "") (lower .Values.source) | quote }}
                - name: NO_PROXY
                  value: "localhost,127.0.0.1,kubernetes.default.svc,kubernetes.default.svc.cluster.local"
                - name: no_proxy
                  value: "localhost,127.0.0.1,kubernetes.default.svc,kubernetes.default.svc.cluster.local"
                - name: AWS_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Release.Name }}-credentials
                      key: AWS_ACCESS_KEY_ID
                - name: AWS_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Release.Name }}-credentials
                      key: AWS_SECRET_ACCESS_KEY
                - name: AWS_ENDPOINT_URL
                  value: {{ .Values.s3.endpointUrl | quote }}
              resources:
                {{- toYaml .Values.resources.transform | nindent 16 }}
              command:
                - /bin/sh
                - -c
              args:
                - >
                  EXTRACT_PATH="${S3_PATH}/$(date +%Y-%m-%d).parquet";
                  OUTPUT_PATH="${S3_PATH}/$(date +%Y-%m-%d)-converted.parquet";
                  if aws s3 ls s3://${OUTPUT_PATH}/_SUCCESS --endpoint-url=$AWS_ENDPOINT_URL; then
                    echo "Parquet file already exists, skipping."
                    exit 0
                  fi;
                  /opt/spark/bin/spark-submit
                  --master
                  local[*]
                  --driver-memory
                  {{ .Values.spark.resources.transform.driverMemory | quote }}
                  --name
                  etl-job-transform-$SOURCE
                  --conf
                  spark.jars.ivy=/tmp/.ivy
                  --conf
                  spark.hadoop.fs.s3a.endpoint="$AWS_ENDPOINT_URL"
                  --conf
                  spark.hadoop.fs.s3a.path.style.access=true
                  --conf
                  spark.hadoop.fs.s3a.access.key="$(AWS_ACCESS_KEY_ID)"
                  --conf
                  spark.hadoop.fs.s3a.secret.key="$(AWS_SECRET_ACCESS_KEY)"
                  local:///src/etljobs/main.py
                  --job
                  job-$SOURCE
                  --job-args
                  s3a://$EXTRACT_PATH
                  s3a://$OUTPUT_PATH
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-load-job
spec:
  schedule: {{ .Values.schedule | quote }}
  timeZone: {{ .Values.timeZone | quote }}
  suspend: {{ .Values.suspend }}
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          initContainers:
            - name: wait-for-transform
              image: amazon/aws-cli
              env:
                - name: AWS_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Release.Name }}-credentials
                      key: AWS_ACCESS_KEY_ID
                - name: AWS_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Release.Name }}-credentials
                      key: AWS_SECRET_ACCESS_KEY
                - name: AWS_ENDPOINT_URL
                  value: {{ .Values.s3.endpointUrl | quote }}
                - name: S3_PATH
                  value: {{ printf "%s/%s" (.Values.s3.basePath | replace "s3://" "") (lower .Values.source) | quote }}
                - name: COLLECTIONS_PATH
                  value: {{ .Values.s3.collectionsPath | replace "s3://" "" | quote }}
              command: ["sh", "-c"]
              args:
                - >
                  OUTPUT_PATH="${S3_PATH}/$(date +%Y-%m-%d)-converted.parquet";
                  until aws s3 ls s3://${OUTPUT_PATH}/_SUCCESS --endpoint-url=$AWS_ENDPOINT_URL && aws s3 ls s3://$COLLECTIONS_PATH --endpoint-url=$AWS_ENDPOINT_URL; do sleep 10; done
          containers:
            - name: spark-submit
              image: {{ printf "%s:%s" .Values.image.repository .Values.image.tag }}
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              env:
                - name: SOURCE
                  value: {{ .Values.source | quote }}
                - name: S3_PATH
                  value: {{ printf "%s/%s" (.Values.s3.basePath | replace "s3://" "") (lower .Values.source) | quote }}
                - name: NO_PROXY
                  value: "localhost,127.0.0.1,kubernetes.default.svc,kubernetes.default.svc.cluster.local"
                - name: no_proxy
                  value: "localhost,127.0.0.1,kubernetes.default.svc,kubernetes.default.svc.cluster.local"
                - name: DATAVERSE_API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Release.Name }}-credentials
                      key: DATAVERSE_API_KEY
                - name: AWS_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Release.Name }}-credentials
                      key: AWS_ACCESS_KEY_ID
                - name: AWS_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Release.Name }}-credentials
                      key: AWS_SECRET_ACCESS_KEY
                - name: AWS_ENDPOINT_URL
                  value: {{ .Values.s3.endpointUrl | quote }}
                - name: DATAVERSE_HOST
                  value: {{ .Values.dataverse.host | quote }}
                - name: COLLECTIONS_PATH
                  value: {{ .Values.s3.collectionsPath | replace "s3://" "" | quote }}
              resources:
                {{- toYaml .Values.resources.load | nindent 16 }}
              command:
                - /bin/sh
                - -c
              args:
                - >
                  OUTPUT_PATH="${S3_PATH}/$(date +%Y-%m-%d)-converted.parquet";
                  /opt/spark/bin/spark-submit
                  --master
                  local[*]
                  --name
                  etl-job-load-$SOURCE
                  --conf
                  spark.jars.ivy=/tmp/.ivy
                  --conf
                  spark.hadoop.fs.s3a.endpoint="$AWS_ENDPOINT_URL"
                  --conf
                  spark.hadoop.fs.s3a.path.style.access=true
                  --conf
                  spark.hadoop.fs.s3a.access.key="$(AWS_ACCESS_KEY_ID)"
                  --conf
                  spark.hadoop.fs.s3a.secret.key="$(AWS_SECRET_ACCESS_KEY)"
                  local:///src/etljobs/main.py
                  --job
                  submit_dataverse
                  --job-args
                  s3a://$OUTPUT_PATH
                  $DATAVERSE_HOST
                  $(DATAVERSE_API_KEY)
                  s3://$COLLECTIONS_PATH
                  --threads={{ .Values.spark.jobArguments.load.threads }}
                  {{- if .Values.spark.jobArguments.load.skipCollectionUpdates }}
                  --skip-collection-updates
                  {{- end }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-publish-job
spec:
  schedule: {{ .Values.schedule | quote }}
  timeZone: {{ .Values.timeZone | quote }}
  suspend: {{ .Values.suspend }}
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          initContainers:
            - name: wait-for-load
              image: {{ printf "ghcr.io/nfdi4health/csh-etl-pipeline:%s" .Values.image.tag }}
              env:
                - name: AWS_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Release.Name }}-credentials
                      key: AWS_ACCESS_KEY_ID
                - name: AWS_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Release.Name }}-credentials
                      key: AWS_SECRET_ACCESS_KEY
                - name: AWS_ENDPOINT_URL
                  value: {{ .Values.s3.endpointUrl | quote }}
                - name: S3_PATH
                  value: {{ printf "%s/%s" (.Values.s3.basePath | replace "s3://" "") (lower .Values.source) | quote }}
              command: ["/bin/sh", "-c"]
              args:
                - >
                  CHECKPOINT_PATH="${S3_PATH}/$(date +%Y-%m-%d)-checkpoint";
                  until aws s3 ls s3://${CHECKPOINT_PATH}/_SUCCESS --endpoint-url=$AWS_ENDPOINT_URL; do sleep 10; done
          containers:
            - name: spark-submit
              image: {{ printf "%s:%s" .Values.image.repository .Values.image.tag }}
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              env:
                - name: SOURCE
                  value: {{ .Values.source | quote }}
                - name: DATAVERSE_HOST
                  value: {{ .Values.dataverse.host | quote }}
                - name: DATAVERSE_API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Release.Name }}-credentials
                      key: DATAVERSE_API_KEY
              command:
                - "python3"
                - "-u" # unbuffered, so logs are immediately flushed
                - "scripts/publish_all_datasets.py"
                - "-d"
                - "$DATAVERSE_HOST"
                - "-k"
                - "$(DATAVERSE_API_KEY)"
                - "-t"
                - "updatecurrent"
                - "-c"
                - "$SOURCE"
