api:
  backend_mode:
  dataverse_oidc_id:
  dataverse_host:
ingress:
  dns:
  enableSSL: false
  certIssuer:
oidc:
  frontend:
    clientid:
    authority:
  backend:
    clientid:
    secret:
    introspect:
images:
  backend: ghcr.io/nfdi4health/csh-ui/backend:dd54d34a33307e996407c426993b35fd44e08fb7
  frontend: ghcr.io/nfdi4health/csh-ui/frontend:dd54d34a33307e996407c426993b35fd44e08fb7