api:
  default_token:
  default_project:
ingress:
  #dns: "csh.qa.km.k8s.zbmed.de"
  enableSSL: false
  enableHtacess: false
  certIssuer: "letsencrypt-prod"
oidc:
  frontend:
    clientid:
    authority:
  backend:
    clientid:
    secret:
    introspect:
images:
  backend: ghcr.io/nfdi4health/csh-ui/backend:cc55228ba4de299e592ac61d6667183d4355f123
  frontend: ghcr.io/nfdi4health/csh-ui/frontend:cc55228ba4de299e592ac61d6667183d4355f123
  seek: ghcr.io/nfdi4health/seek:csh@sha256:fedc171f84c37a00620823dcb5962442088d80adc6125915cedf7712d759d075