api:
  backend_mode:
  dataverse_oidc_id:
  dataverse_host:
  dataverse_admin_api_key:
  unblock_key:
frontend:
  userback_access_token:
  seoRenderer:
    enabled: true
    replicaCount: 1
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 256Mi
ingress:
  dns:
  tls:
    enabled: false
    # Additional DNS names to include in the TLS certificate. If empty, the
    # ingress DNS name is used
    hosts: []
    # If empty, defaults to <release-name>-tls-secret
    secretName:
    # Optional
    certIssuer:
  basicAuth:
    enabled: false
    username:
    password:
oidc:
  frontend:
    clientid:
    authority:
  backend:
    clientid:
    secret:
    introspect:
    user_url:
    oidc_connect_url:
images:
  backend: ghcr.io/nfdi4health/csh-ui/backend:master
  frontend: ghcr.io/nfdi4health/csh-ui/frontend:master
  seoRenderer: ghcr.io/nfdi4health/csh-ui/frontend-seo:master
