apiVersion: v1
kind: ConfigMap
metadata:
  name: etl-job-config
  namespace: $NAMESPACE
data:
  AWS_ENDPOINT_URL: "$AWS_ENDPOINT_URL"
  DATAVERSE_HOST: "$DATAVERSE_HOST"
  S3_PATH: "$S3_PATH"
  COLLECTIONS_PATH: "$COLLECTIONS_PATH"