apiVersion: v1
kind: Secret
metadata:
  name: etl-job-credentials
  namespace: $NAMESPACE
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "$AWS_ACCESS_KEY_ID"
  AWS_SECRET_ACCESS_KEY: "$AWS_SECRET_ACCESS_KEY"
  DATAVERSE_API_KEY: "$DATAVERSE_API_KEY"